version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassword123!
    ports:
      - "1433:1433"

  backend:
    build:
      context: ./.Net
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseProvider=SqlServer
      - ConnectionStrings__SqlServerConnection=Server=db;Database=StockApp;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True;
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
