// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockApp.Infrastructure.Database;

#nullable disable

namespace StockApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501100529_AddFinancialGoals")]
    partial class AddFinancialGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockApp.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountID = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Balance = 1000m,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            AccountID = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Balance = 1000m,
                            DateOfBirth = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("StockApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "admin@test.com"
                        },
                        new
                        {
                            UserID = new Guid("00000000-0000-0000-0000-000000000002"),
                            Email = "admin1@test.com"
                        });
                });

            modelBuilder.Entity("StockApp.Domain.Entities.BuyOrder", b =>
                {
                    b.Property<Guid>("BuyOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndTimeOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BuyOrderID");

                    b.HasIndex("OrderStatusID");

                    b.HasIndex("UserID");

                    b.ToTable("BuyOrders");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Cash", b =>
                {
                    b.Property<Guid>("CashID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CashID");

                    b.HasIndex("AccountID");

                    b.ToTable("CashAllocations");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.FinancialGoal", b =>
                {
                    b.Property<Guid>("FinancialGoalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("GoalTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FinancialGoalID");

                    b.HasIndex("GoalTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("FinancialGoals");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.GoalType", b =>
                {
                    b.Property<Guid>("GoalTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GoalTypeID");

                    b.ToTable("GoalTypes");

                    b.HasData(
                        new
                        {
                            GoalTypeID = new Guid("30000000-0000-0000-0000-000000000001"),
                            Name = "Retirement"
                        },
                        new
                        {
                            GoalTypeID = new Guid("30000000-0000-0000-0000-000000000002"),
                            Name = "University"
                        },
                        new
                        {
                            GoalTypeID = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "Emergency Fund"
                        },
                        new
                        {
                            GoalTypeID = new Guid("30000000-0000-0000-0000-000000000004"),
                            Name = "Vacation"
                        },
                        new
                        {
                            GoalTypeID = new Guid("30000000-0000-0000-0000-000000000005"),
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("StockApp.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<Guid>("OrderStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderStatusID");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            OrderStatusID = new Guid("20000000-0000-0000-0000-000000000001"),
                            StatusName = "Pending"
                        },
                        new
                        {
                            OrderStatusID = new Guid("20000000-0000-0000-0000-000000000002"),
                            StatusName = "Authorized"
                        },
                        new
                        {
                            OrderStatusID = new Guid("20000000-0000-0000-0000-000000000003"),
                            StatusName = "Processed"
                        },
                        new
                        {
                            OrderStatusID = new Guid("20000000-0000-0000-0000-000000000004"),
                            StatusName = "Canceled"
                        });
                });

            modelBuilder.Entity("StockApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.HasKey("Token");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.SellOrder", b =>
                {
                    b.Property<Guid>("SellOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndTimeOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SellOrderID");

                    b.HasIndex("OrderStatusID");

                    b.HasIndex("UserID");

                    b.ToTable("SellOrders");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.UserDetails", b =>
                {
                    b.Property<Guid>("DetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Building")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DetailsID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.UserOperation", b =>
                {
                    b.Property<Guid>("UserOperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StockSymbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserOperationID");

                    b.HasIndex("UserID");

                    b.ToTable("UserOperations");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleID = new Guid("10000000-0000-0000-0000-000000000001"),
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleID = new Guid("10000000-0000-0000-0000-000000000002"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = new Guid("10000000-0000-0000-0000-000000000003"),
                            RoleName = "Advisor"
                        });
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Account", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Account")
                        .HasForeignKey("StockApp.Domain.Entities.Account", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.BuyOrder", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockApp.Domain.Entities.ApplicationUser", null)
                        .WithMany("BuyOrders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Cash", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.Account", "Account")
                        .WithMany("CashAllocations")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.FinancialGoal", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.GoalType", "GoalType")
                        .WithMany()
                        .HasForeignKey("GoalTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockApp.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.SellOrder", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockApp.Domain.Entities.ApplicationUser", null)
                        .WithMany("SellOrders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.UserDetails", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("StockApp.Domain.Entities.UserDetails", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockApp.Domain.Entities.UserOperation", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.ApplicationUser", null)
                        .WithMany("UserOperations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Account", b =>
                {
                    b.Navigation("CashAllocations");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("BuyOrders");

                    b.Navigation("SellOrders");

                    b.Navigation("UserOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
